name: Run AML Pipeline

on:
  push:
    branches:
      - main

jobs:
  submit-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Azure ML CLI extension
        run: |
          pip install azure-cli
          az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Submit AML pipeline
        run: |
          az ml job create \
            --file pipeline.yml \
            --resource-group rg-60302087 \
            --workspace-name GoodReadsReviewsAnalysis-60302087
